# SlimStorage Configuration Template
# Copy this file to .secrets.yml and fill in your actual values
# WARNING: Never commit .secrets.yml to version control!

# Database Configuration
database:
  host: localhost
  port: 3306
  name: your_database_name
  user: your_database_user
  password: your_database_password
  prefix: slimstore_
  url: https://your-server.com/mysqladmin/  # Optional: Link to database admin panel

# Domain Configuration
domain:
  name: services.yourdomain.com
  public_folder: /www/public/  # Optional: For FTP deployment scripts

# Google OAuth Configuration
# Get credentials from: https://console.cloud.google.com/apis/credentials
google_oauth:
  client_id: YOUR_GOOGLE_CLIENT_ID.apps.googleusercontent.com
  client_secret: GOCSPX-YOUR_CLIENT_SECRET
  redirect_uri: https://services.yourdomain.com/admin/callback.php

# Superadmin Configuration
superadmin:
  email: admin@example.com
  contact_email: support@yourdomain.com  # Optional: Public contact email

# API Configuration
api:
  rate_limit_requests: 10000        # Max requests per window
  rate_limit_window_seconds: 60     # Rate limit window in seconds
  max_keys_per_user: 100            # Max API keys per user
  max_value_size_bytes: 262144      # Max value size (256 KB)
  allowed_origins: https://services.yourdomain.com  # CORS origins (comma-separated)
  log_mode: full                    # Optional: full, errors, sample, none

# FTP Configuration (Optional - for deployment scripts)
ftp:
  user: your_ftp_user
  password: your_ftp_password
  protocol: ftp://your-ftp-server.com
  url: https://webftp.example.com/
